//Add Post
export const REQUEST_ADD_FEED = "REQUEST_ADD_FEED";
export const SUCCESS_ADD_FEED = "SUCCESS_ADD_FEED";
export const FAILURE_ADD_FEED = "FAILURE_ADD_FEED";

//Update Post
export const REQUEST_UPDATE_FEED = "REQUEST_UPDATE_FEED";
export const SUCCESS_UPDATE_FEED = "SUCCESS_UPDATE_FEED";
export const FAILURE_UPDATE_FEED = "FAILURE_UPDATE_FEED";
