//login
export const REQUEST_USER_DETAILS = 'REQUEST_USER_DETAILS';
export const SUCCESS_USER_DETAILS = 'SUCCESS_USER_DETAILS';
export const FAILURE_USER_DETAILS = 'FAILURE_USER_DETAILS';
//Register
export const REQUEST_USER_REGISTRATION = 'REQUEST_USER_REGISTRATION';
export const SUCCESS_USER_REGISTRATION = 'SUCCESS_USER_REGISTRATION';
export const FAILURE_USER_REGISTRATION = 'FAILURE_USER_REGISTRATION';
//Add Post
export const REQUEST_ADD_FEED = 'REQUEST_ADD_FEED';
export const SUCCESS_ADD_FEED = 'SUCCESS_ADD_FEED';
export const FAILURE_ADD_FEED = 'FAILURE_ADD_FEED';

//Update Post
export const REQUEST_UPDATE_FEED = 'REQUEST_UPDATE_FEED';
export const SUCCESS_UPDATE_FEED = 'SUCCESS_UPDATE_FEED';
export const FAILURE_UPDATE_FEED = 'FAILURE_UPDATE_FEED';

//mera
export const DEFAULT_CASE = 'DEFAULT_CASE';
export const TAB_SELECT = 'TAB_SELECT';
export const SET_USER = 'SET_USER';
export const SET_FORM_FIELD_VALUE = 'SET_FORM_FIELD_VALUE';
export const CLEAR_FORM = 'CLEAR_FORM';
